version: '3'

services:
  postgresql:
    image: postgres:12
    container_name: postgres-dev-sb
    ports:
      - "5432:5432"
    networks:
      - sb-course-network
    environment:
      - POSTGRES_PASSWORD=1234567

  pgadmin:
    image: dpage/pgadmin4:4
    container_name: pgadmin-dev-sb
    ports:
      - "80:80"
    networks:
      - sb-course-network
    environment:
      - "PGADMIN_DEFAULT_EMAIL=dev@localhost"
      - "PGADMIN_DEFAULT_PASSWORD=dev"
    depends_on:
      - postgresql
 
networks:
  sb-course-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
    external: false
